### PR TITLE
chores(README): fenced code blocks should be surrounded by blank lines

### PR DESCRIPTION
**Pull request by kianmeng**
See MD031 at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md

### CODE REVIEW

**Comment by jeertmans** [comment]
Hi @kianmeng, thanks for your pull request!

I agree that your reference holds good reasons to stick to that rule number 31.

Maybe it is worth creating a github action that runs this lint ? 
If you would like to do it, please do :) (there are many other examples in the .github/workflows directory)
Otherwise I can do it!

**Comment by kianmeng** [comment]
> Maybe it is worth creating a github action that runs this lint ? If you would like to do it, please do :) (there are many other examples in the .github/workflows directory) Otherwise I can do it!

There are still some underlying issues that I can't resolve, which depends on your personal takes. Hence, it's better that you implement this. :smile: 

```sh
$ mdl README.md 
README.md:133: MD004 Unordered list style
README.md:137: MD004 Unordered list style
README.md:138: MD004 Unordered list style
README.md:5: MD013 Line length
README.md:21: MD013 Line length
README.md:23: MD013 Line length
README.md:29: MD013 Line length
README.md:100: MD013 Line length
README.md:133: MD013 Line length
README.md:137: MD013 Line length
README.md:138: MD013 Line length
README.md:109: MD024 Multiple headers with the same content
README.md:11: MD029 Ordered list item prefix
README.md:12: MD029 Ordered list item prefix
README.md:14: MD029 Ordered list item prefix
README.md:15: MD029 Ordered list item prefix
README.md:16: MD029 Ordered list item prefix

A detailed description of the rules is available at https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md
```

**Comment by jeertmans** [comment]
Merged! Thanks, @kianmeng ! Finally, I decided to add a GitHub action directly in this PR so that I avoid multiple PRs ;-)

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
