### PR TITLE
feat: implement hash for types in check

### PR DESCRIPTION
**Pull request by ModProg**
# Description

derive hash on types in check

## Check List (Check all the applicable boxes)

- [x] I understand that my contributions needs to pass the checks.
- [ ] If I created new functions / methods, I documented them and add type hints.
- [ ] If I modified already existing code, I updated the documentation accordingly.
- [x] The title of my pull request is a short description of the requested changes.

### CODE REVIEW

**Comment by jeertmans** [comment]
Hello @ModProg, thank you for your suggestion!
Can I ask what are the motivations behind being able to hash such structure?

**Comment by ModProg** [comment]
I want to cache the results of spellchecking, and want to store the request in a structure that uses hashing.

There might be better ways to do this (I could probably hash the text itself), but due to how my code is structured, this was the simplest solution, and greatly improved real-time performance in my testing.

**Comment by jeertmans** [comment]
Ok I get the point :)
But then shouldn’t it be restricted to the request structures? We never need to hash the responses in that cases.

**Comment by ModProg** [comment]
true, I added it everywhere because I thought it shouldn't matter, but I can restrict it to what I strictly need.

**Comment by jeertmans** [comment]
> true, I added it everywhere because I thought it shouldn't matter, but I can restrict it to what I strictly need.

Then I prefer not to derive traits that are likely not needed :-)

If you can remove the derive macros from response structs, and maybe also add a derive `Hash` to other requests, so we cover all the request structs?

Then I can merge this :-) Thanks for your work!

**Comment by ModProg** [comment]
done

**Review by jeertmans — APPROVED** [review]

**Comment by jeertmans** [comment]
Thanks for you contribution @ModProg !

**Pull request merged**
